version: '3.1'
services:
  mavenwebapp:
    image: hemeshwar2702docker/maven-composefile:VERSION
    restart: always
    ports:
    - 9091:8080
    networks:
    - mavenappbridge
networks:
  mavenappbridge:
