version: '3.1'
services:
  springboot:
    image: hemeshwar2702docker/maven-composefile:VERSION
    restart: always
    ports:
    - 9090:8080
    networks:
    - mavenappbridge
networks:
  mavenappbridge:
